---
title: "Fig.S6. Robustness analyses of longitudinal head motion effects on ADHD energy deviations"
author:
  - name: Hang Yang
    orcid: 0000-0002-7349-3366
    email: yanghang@cibr.ac.cn
    url: https://scholar.google.com/citations?user=LqI72qAAAAAJ&hl
    affiliation: 
      - name: Chinese Institute for Brain Research, Beijing (CIBR)
        group: CUIZAIXU Lab
        url: https://cuilab.cibr.ac.cn/
date: "2026-01-05"
format: 
  html:
    code-fold: true
    code-tools: true
    theme: Materia
    toc: true
    toc_depth: 3
    toc-expand: 1
    toc_float: true
    toc-location: left
    number-sections: true
    number-depth: 3
    embed-resources: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Load required libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(psych)
  library(effectsize)
  library(ggplot2)
  library(ggseg)
  library(ggsegSchaefer)
  library(data.table)
  library(compareGroups)
  library(scales)
  library(RColorBrewer)
})

rm(list = ls())
options(warn = -1)

# Define paths and parameters
root_path <- "F:/Cui_Lab/Projects/ABCD_ADHD_Control_Energy/"
behav_path <- paste0(root_path, "data/sub_info/")
task_contrast <- "all0In_2Back0Back"
atlas <- "schaefer400"
outpath <- file.path(root_path, "results", task_contrast, atlas)

# Define color palette
color_palette <- rev(brewer.pal(n = 3, name = "RdBu"))[c(1, 3)]
```

## Data Preparation

```{r load_data}
# Load energy deviation data
load(file.path(outpath, "energy_deviation.RData"))

# Load demographic and biotype information
sub_demo_info <- fread(paste0(behav_path, "sub_demo_info_train_test.csv"), na.strings = c("", "NA"))
sub_test_info <- filter(sub_demo_info, usage == "test")
sub_train_info <- filter(sub_demo_info, usage == "train")

# Merge biotype information
biotype_info <- read.csv(paste0(outpath, "/adhd_biotype_info.csv"))
sub_test_info <- merge(sub_test_info, biotype_info[, c("src_subject_id", "biotype")], by = "src_subject_id", all.x = TRUE)
sub_test_info$W_scores_wholebrain <- W_scores_wholebrain
```

## Data Analysis

```{r prepare_longitudinal_data}
# Define CBCL variables
cbcl_vars <- c("cbcl_scr_syn_attention_t", "cbcl_scr_syn_external_t")

# Identify ADHD subjects at baseline with 2-year follow-up data
sub_adhd_0y <- sub_test_info %>% 
  filter(diagnosis == "adhd" & eventname == "baseline_year_1_arm_1") %>%
  pull(src_subject_id)

adhd_long_data <- sub_test_info %>%
  filter(src_subject_id %in% sub_adhd_0y) %>%
  group_by(src_subject_id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  mutate(eventname = factor(eventname, levels = c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1")))
```


```{r paired_ttest_biotype1}
adhd_0y <- adhd_long_data %>% 
  filter(eventname == "baseline_year_1_arm_1") %>% 
  select(W_scores_wholebrain, mean_fd)

adhd_2y <- adhd_long_data %>% 
  filter(eventname == "2_year_follow_up_y_arm_1") %>% 
  select(W_scores_wholebrain, mean_fd)

adhd_diff <- adhd_2y - adhd_0y
cor.test(adhd_diff$W_scores_wholebrain, adhd_diff$mean_fd)

```

```{r plot_corrl}
# Scatter plot:
p <- ggplot(adhd_diff, aes(x = W_scores_wholebrain, y = mean_fd)) + 
  geom_point() +
  geom_smooth(method = lm, color = "black") +
  labs(x = "ΔEnergy deviation", y = "ΔHead motion") +
  theme_classic() + 
  theme(
    strip.text = element_text(size = 18),
    axis.text = element_text(size = 18, color = "black"),
    axis.title = element_text(size = 18),
    axis.title.x = element_text(margin = margin(t = 8)),
    aspect.ratio = 0.9
  )

print(p)
ggsave(file.path(outpath, "corr_fd_deviation_adhd_2y_0y_change.png"), 
       plot = p, width = 9, height = 9, units = "cm", dpi = 1200)
```