---
title: "Energy Deviation Null Model"
author:
  - name: Hang Yang
    orcid: 0000-0002-7349-3366
    email: yanghang@cibr.ac.cn
    url: https://scholar.google.com/citations?user=LqI72qAAAAAJ&hl
    affiliation: 
      - name: Chinese Institute for Brain Research, Beijing (CIBR)
        group: CUIZAIXU Lab
        url: https://cuilab.cibr.ac.cn/
date: "2026-01-05"
format: 
  html:
    code-fold: true
    code-tools: true
    theme: Materia
    toc: true
    toc_depth: 3
    toc-expand: 1
    toc_float: true
    toc-location: left
    number-sections: true
    number-depth: 3
    embed-resources: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Load required libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(psych)
  library(effectsize)
  library(ggplot2)
  library(ggseg)
  library(ggsegSchaefer)
  library(SNFtool)
  library(data.table)
  library(scales)
})

rm(list = ls())
options(warn = -1)

# Source custom functions
source("F:/Cui_Lab/Projects/ABCD_ADHD_Control_Energy/functions/energy_summary_combat.R")
source("F:/Cui_Lab/Projects/ABCD_ADHD_Control_Energy/functions/plot_surface.R")
source("F:/Cui_Lab/Projects/ABCD_ADHD_Control_Energy/functions/calc_w_scores.R")

# Define paths and parameters
root_path <- "F:/Cui_Lab/Projects/ABCD_ADHD_Control_Energy/"
behav_path <- paste0(root_path, "data/sub_info/")
task_contrast <- "all0In_2Back0Back"
atlas <- "schaefer400"
combat_type <- "combat"
energy_norm <- "control_energy"
outpath <- file.path(root_path, "results", task_contrast, atlas)
dir.create(outpath, recursive = TRUE, showWarnings = FALSE)
```

## Data Preparation

```{r load_subject_info}
# Load demographic information
sub_demo_info <- fread(paste0(behav_path, "sub_demo_info_train_test.csv"), na.strings = c("", "NA"))

# Remove subjects with missing usage information
idx_nonNA <- which(!is.na(sub_demo_info$usage))
sub_demo_info <- sub_demo_info[idx_nonNA, ]

# Split into train and test sets
sub_test_info <- filter(sub_demo_info, usage == "test")
sub_train_info <- filter(sub_demo_info, usage == "train")
```

## Real Energy Data

### Calculate Real Energy

```{r calculate_real_energy}
# Calculate control energy at whole-brain, network, and regional levels
energy_data <- energy_summary(root_path, task_contrast, atlas = atlas, combat = combat_type, energy_norm = energy_norm)
energy_roi <- energy_data$ROI[idx_nonNA, ]
energy_network <- energy_data$NetAvg[idx_nonNA, ]
energy_wholebrain <- as.data.frame(energy_data$WholeBrain[idx_nonNA, ])
colnames(energy_wholebrain) <- "WholeBrain"
```

### Prepare Training Data

```{r prepare_train_data}
# Define covariates for W-score calculation
covariates <- c("age", "sex", "handedness", "mean_fd", "TBV", paste0("network_strength_", atlas))
behav_data <- sub_demo_info[, ..covariates]
train_idx <- which(sub_demo_info$usage == "train")

# Prepare training data at whole-brain level
lm_data <- cbind(energy_wholebrain, behav_data)
train_data_wholebrain <- lm_data[train_idx, ]

# Prepare training data at network level
lm_data <- cbind(energy_network, behav_data)
train_data_network <- lm_data[train_idx, ]

# Prepare training data at ROI level
lm_data <- cbind(energy_roi, behav_data)
train_data_roi <- lm_data[train_idx, ]
```

## Null Model Energy Data

### Define Null Energy Function

```{r define_null_function}
# Function to load null model energy data for a single iteration
energy_summary_null <- function(working_dir, task_contrast, atlas, combat, iter, energy_norm) {
  file_name <- paste0("ABCD_", task_contrast, "_", atlas, "_", iter)
  schaefer_label <- read.csv(paste0(working_dir, "data/parcellation/", atlas, "_subcortical_region_labels.csv"))
  network_label <- schaefer_label$Net_Label
  
  # Load energy data
  energy_file <- if (combat == "") {
    paste0(working_dir, "data/", energy_norm, "/", file_name, ".csv")
  } else {
    paste0(working_dir, "data/", energy_norm, "/", file_name, "_", combat, ".csv")
  }
  energy_roi <- read.csv(energy_file)
  colnames(energy_roi) <- schaefer_label$ROI_Label
  
  # Calculate network-level energy
  n_subjects <- nrow(energy_roi)
  network_names <- c("VS", "SM", "DA", "VA", "LM", "FP", "DM", "SC")
  energy_network <- data.frame(matrix(NA, nrow = n_subjects, ncol = 8))
  colnames(energy_network) <- network_names
  for (i in 1:8) {
    network_idx <- which(network_label == i)
    energy_network[, i] <- rowMeans(energy_roi[, network_idx])
  }
  
  # Calculate whole-brain energy
  energy_wholebrain <- as.data.frame(rowMeans(energy_roi))
  colnames(energy_wholebrain) <- "WholeBrain"
  
  return(list(ROI = energy_roi, NetAvg = energy_network, WholeBrain = energy_wholebrain))
}
```

### Load Null Energy Data

```{r load_null_energy}
# Load null model energy across 101 iterations
energy_norm_null <- "control_energy_null"
energy_null_list <- vector("list", 101)
pb <- txtProgressBar(min = 0, max = 101, style = 3)

for (i in 1:101) {
  iter_name <- sprintf("iter%03d", i)
  energy_null_list[[i]] <- energy_summary_null(working_dir = root_path, task_contrast = task_contrast, 
                                               atlas = atlas, combat = combat_type, iter = iter_name, 
                                               energy_norm = energy_norm_null)
  setTxtProgressBar(pb, i)
}
close(pb)
```

### Calculate Null W-scores

```{r calculate_null_wscores}
# Load null demographic information
sub_test_info <- fread(paste0(behav_path, "sub_test_info.csv"))
behav_data_null <- sub_test_info[, ..covariates]

# Calculate W-scores for each null iteration
W_scores_null_wholebrain <- vector("list", 101)
W_scores_null_network <- vector("list", 101)
W_scores_null_roi <- vector("list", 101)

pb <- txtProgressBar(min = 0, max = 101, style = 3)

for (i in 1:101) {
  energy_tmp <- energy_null_list[[i]]
  
  # Whole-brain level
  energy_data_null <- energy_tmp$WholeBrain
  test_data_wholebrain <- cbind(energy_data_null, behav_data_null)
  W_scores_null_wholebrain[[i]] <- calc_w_scores(train_data_wholebrain, test_data_wholebrain, covariates)
  
  # Network level
  energy_data_null <- energy_tmp$NetAvg
  test_data_network <- cbind(energy_data_null, behav_data_null)
  W_scores_null_network[[i]] <- calc_w_scores(train_data_network, test_data_network, covariates)
  
  # ROI level
  energy_data_null <- energy_tmp$ROI
  test_data_roi <- cbind(energy_data_null, behav_data_null)
  W_scores_null_roi[[i]] <- calc_w_scores(train_data_roi, test_data_roi, covariates)
  
  setTxtProgressBar(pb, i)
}
close(pb)

# Save results
save(energy_null_list, W_scores_null_wholebrain, W_scores_null_network, W_scores_null_roi, sub_test_info,
     file = file.path(outpath, "energy_deviation_null.RData"))
```